import type { HeroContent, HeroCard } from "@/lib/hero-types";

export const DEFAULT_HERO_CONTENT: HeroContent = {
  id: 1,
  backgroundImagePublicId: null,
  cardFallbackImagePublicId: null,
  eyebrow: "Dexta Synergy Services",
  headline: "Saturating our world with Imprints of value",
  body: "From identity systems to digital products to premium print, we shape launches that feel sharp, connected, and impossible to ignore.",
  ctaText: "See Our Work",
  ctaHref: "/projects",
  stackBadge: "Dexta service stack",
  stackTitle: "Your brand, reimagined",
  stackBody:
    "Design sharper, ship faster, and carry one clear idea from screen to print without losing the visual thread in between.",
  stackCtaText: "Start a Project",
  stackCtaHref: "/contact",
  updatedAt: new Date(0),
};

export const DEFAULT_HERO_CARDS: HeroCard[] = [
  {
    id: "hero-card-left",
    position: 0,
    href: "/projects?tab=design",
    imagePublicId: null,
    objectPosition: "center",
    label: "IDENTITY",
    title: "DESIGN",
    chip: "Brand systems",
    badge: "ID",
    metaTitle: "Brand identity",
    metaSubtitle: "Identity / UI / Motion",
    isVisible: true,
    createdAt: new Date(0),
    updatedAt: new Date(0),
  },
  {
    id: "hero-card-center",
    position: 1,
    href: "/projects?tab=build",
    imagePublicId: null,
    objectPosition: "center",
    label: "DIGITAL",
    title: "BUILD",
    chip: "Product launches",
    badge: "WB",
    metaTitle: "Digital engineering",
    metaSubtitle: "Next.js / React / Conversion-first UX",
    isVisible: true,
    createdAt: new Date(0),
    updatedAt: new Date(0),
  },
  {
    id: "hero-card-right",
    position: 2,
    href: "/projects?tab=print",
    imagePublicId: null,
    objectPosition: "center",
    label: "PHYSICAL",
    title: "PRINT",
    chip: "Campaign assets",
    badge: "PR",
    metaTitle: "Print and merch",
    metaSubtitle: "Banners / Packaging / Apparel",
    isVisible: true,
    createdAt: new Date(0),
    updatedAt: new Date(0),
  },
];
