import {
  backgroundImageField,
  colorField,
  imageField,
  linkField,
  model3dField,
  numberField,
  textField,
  textareaField,
  type SchoolTemplateManifest,
} from "./types";

const pageHero = {
  id: "page-hero",
  label: "Page Hero",
  selector: ".school-page-hero",
  fields: [
    textField("eyebrow", "Eyebrow", ".section-kicker"),
    textField("title", "Title", "h1"),
    textareaField("body", "Body", "p"),
  ],
};

export const dextaAcademy4Manifest = {
  templateSlug: "dexta-academy-4",
  templateName: "Dexta Academy 4",
  sourceDir: "public/dexta-academy-4",
  entryFile: "index.html",
  previewPath: "/dexta-academy-4/index.html",
  assetInventory: {
    directories: ["assets", "css", "fonts", "js"],
    stylesheets: ["css/style.css", "css/hero-3d.css", "css/gallery-page.css"],
    scripts: ["js/main.js", "js/hero-3d.js"],
  },
  sharedSections: [
    {
      id: "header",
      label: "Header",
      selector: ".hero-header",
      fields: [
        imageField("logo", "Logo", ".hero-brand img"),
        textField("applyText", "Apply button text", ".hero-apply-btn"),
        linkField("applyHref", "Apply button link", ".hero-apply-btn"),
      ],
    },
    {
      id: "footer",
      label: "Footer",
      selector: ".school-footer",
      fields: [
        imageField("logo", "Footer logo", ".school-footer-brand-logo"),
        textField("schoolName", "School name", ".school-footer-brand h3"),
        textareaField("description", "Description", ".school-footer-brand p"),
        textField("phone", "Phone", "a[href^='tel:']"),
        textField("email", "Email", "a[href^='mailto:']"),
        textareaField(
          "address",
          "Address",
          ".school-footer .col-md-6:nth-of-type(3) p",
        ),
      ],
    },
  ],
  pages: [
    {
      slug: "home",
      fileName: "index.html",
      title: "Home",
      isHome: true,
      sections: [
        {
          id: "hero",
          label: "Hero",
          selector: ".school-hero",
          fields: [
            textField("eyebrow", "Eyebrow", ".hero-eyebrow"),
            textField("headline", "Headline", ".hero-display"),
            textField(
              "primaryCtaText",
              "Primary CTA text",
              ".hero-primary-btn",
            ),
            linkField(
              "primaryCtaHref",
              "Primary CTA link",
              ".hero-primary-btn",
            ),
            textField(
              "secondaryCtaText",
              "Secondary CTA text",
              ".hero-secondary-btn",
            ),
            linkField(
              "secondaryCtaHref",
              "Secondary CTA link",
              ".hero-secondary-btn",
            ),
          ],
        },
        {
          id: "hero-3d-model",
          label: "Hero 3D Model",
          selector: "#hero-3d-stage",
          description:
            "Controls the homepage 3D model source, material colors, scale, scene offset, and responsive stage placement.",
          fields: [
            model3dField("modelUrl", "3D model file", "#hero-3d-stage", {
              configPath: "model.url",
              defaultValue: "assets/3d/gr.glb",
              helpText:
                "Upload an optimized .glb file. The original template uses assets/3d/gr.glb.",
            }),
            colorField("capBodyColor", "Cap body color", "#hero-3d-stage", {
              target: "threeConfig",
              configPath: "materials.capBodyColor",
              defaultValue: "#060d1e",
            }),
            colorField(
              "capBodyEmissiveColor",
              "Cap body glow color",
              "#hero-3d-stage",
              {
                target: "threeConfig",
                configPath: "materials.capBodyEmissiveColor",
                defaultValue: "#010408",
              },
            ),
            colorField(
              "tasselCordColor",
              "Tassel cord color",
              "#hero-3d-stage",
              {
                target: "threeConfig",
                configPath: "materials.tasselCordColor",
                defaultValue: "#2a5fc0",
              },
            ),
            colorField("tasselTipColor", "Tassel tip color", "#hero-3d-stage", {
              target: "threeConfig",
              configPath: "materials.tasselTipColor",
              defaultValue: "#1a3d8a",
            }),
            numberField("modelScale", "Model scale", "#hero-3d-stage", {
              target: "threeConfig",
              configPath: "transform.scale",
              defaultValue: 4.5,
              min: 0.5,
              max: 10,
              step: 0.1,
              helpText:
                "Maps to the Three.js model scale target used after the model is centered.",
            }),
            numberField(
              "modelOffsetX",
              "Model horizontal offset",
              "#hero-3d-stage",
              {
                target: "threeConfig",
                configPath: "transform.offset.x",
                defaultValue: 0.1,
                min: -1,
                max: 1,
                step: 0.01,
                helpText:
                  "Moves the model inside the 3D scene after centering. Positive values move right.",
              },
            ),
            numberField(
              "modelOffsetY",
              "Model vertical offset",
              "#hero-3d-stage",
              {
                target: "threeConfig",
                configPath: "transform.offset.y",
                defaultValue: -0.18,
                min: -1,
                max: 1,
                step: 0.01,
                helpText:
                  "Moves the model inside the 3D scene after centering. Negative values move down.",
              },
            ),
            numberField("rotationX", "Rotation X", "#hero-3d-stage", {
              target: "threeConfig",
              configPath: "transform.rotation.x",
              defaultValue: -0.2,
              min: -3.14,
              max: 3.14,
              step: 0.01,
              unit: "rad",
            }),
            numberField("rotationY", "Rotation Y", "#hero-3d-stage", {
              target: "threeConfig",
              configPath: "transform.rotation.y",
              defaultValue: -0.21,
              min: -3.14,
              max: 3.14,
              step: 0.01,
              unit: "rad",
            }),
            numberField("rotationZ", "Rotation Z", "#hero-3d-stage", {
              target: "threeConfig",
              configPath: "transform.rotation.z",
              defaultValue: 0.2,
              min: -3.14,
              max: 3.14,
              step: 0.01,
              unit: "rad",
            }),
            numberField(
              "desktopStageX",
              "Desktop horizontal position",
              "#hero-3d-stage",
              {
                target: "cssVariable",
                cssVariable: "--cap-center-x",
                scope: "desktop",
                defaultValue: 50,
                min: 0,
                max: 100,
                step: 1,
                unit: "%",
              },
            ),
            numberField(
              "desktopStageY",
              "Desktop vertical position",
              "#hero-3d-stage",
              {
                target: "cssVariable",
                cssVariable: "--cap-center-y",
                scope: "desktop",
                defaultValue: 63,
                min: 0,
                max: 100,
                step: 1,
                unit: "%",
              },
            ),
            numberField(
              "desktopStageWidth",
              "Desktop stage width",
              "#hero-3d-stage",
              {
                target: "cssVariable",
                cssVariable: "--cap-width",
                scope: "desktop",
                defaultValue: 575,
                min: 180,
                max: 900,
                step: 5,
                unit: "px",
              },
            ),
            numberField(
              "desktopStageHeight",
              "Desktop stage height",
              "#hero-3d-stage",
              {
                target: "cssVariable",
                cssVariable: "--cap-height",
                scope: "desktop",
                defaultValue: 380,
                min: 120,
                max: 700,
                step: 5,
                unit: "px",
              },
            ),
            numberField(
              "mobileStageX",
              "Mobile horizontal position",
              "#hero-3d-stage",
              {
                target: "cssVariable",
                cssVariable: "--cap-center-x",
                scope: "mobile",
                defaultValue: 50,
                min: 0,
                max: 100,
                step: 1,
                unit: "%",
              },
            ),
            numberField(
              "mobileStageY",
              "Mobile vertical position",
              "#hero-3d-stage",
              {
                target: "cssVariable",
                cssVariable: "--cap-center-y",
                scope: "mobile",
                defaultValue: 73,
                min: 0,
                max: 100,
                step: 1,
                unit: "%",
              },
            ),
            numberField(
              "mobileStageWidth",
              "Mobile stage width",
              "#hero-3d-stage",
              {
                target: "cssVariable",
                cssVariable: "--cap-width",
                scope: "mobile",
                defaultValue: 286,
                min: 120,
                max: 520,
                step: 5,
                unit: "px",
              },
            ),
            numberField(
              "mobileStageHeight",
              "Mobile stage height",
              "#hero-3d-stage",
              {
                target: "cssVariable",
                cssVariable: "--cap-height",
                scope: "mobile",
                defaultValue: 188,
                min: 90,
                max: 360,
                step: 5,
                unit: "px",
              },
            ),
          ],
        },
        {
          id: "about-preview",
          label: "About Preview",
          selector: ".school-about-preview",
          fields: [
            imageField("image", "Image", ".about-media img"),
            textField("eyebrow", "Eyebrow", ".section-kicker"),
            textField("title", "Title", "h2"),
            textareaField("body", "Body", ".section-copy > p"),
            textField("statValue", "Stat value", ".stat-card strong"),
            textField("statLabel", "Stat label", ".stat-card span"),
            textField("ctaText", "CTA text", ".btn-primary"),
            linkField("ctaHref", "CTA link", ".btn-primary"),
          ],
          repeatable: {
            itemSelector: ".stat-card",
            labelSingular: "Stat",
            labelPlural: "Stats",
          },
        },
        {
          id: "programs",
          label: "Programs",
          selector: ".school-programs",
          fields: [
            textField("eyebrow", "Eyebrow", ".section-kicker"),
            textField("title", "Title", "h2"),
            textareaField("body", "Intro", ".section-intro"),
            backgroundImageField(
              "programImage",
              "Program image",
              ".program-card-image",
            ),
            textField("programTitle", "Program title", ".program-card-body h3"),
            textareaField(
              "programBody",
              "Program body",
              ".program-card-body p",
            ),
            linkField("programHref", "Program link", ".program-card-link"),
          ],
          repeatable: {
            itemSelector: ".program-card",
            labelSingular: "Program card",
            labelPlural: "Program cards",
          },
        },
        {
          id: "gallery-preview",
          label: "Gallery Preview",
          selector: ".homepage-gallery-preview",
          fields: [
            textField("eyebrow", "Eyebrow", ".section-kicker"),
            textField("title", "Title", "h2"),
            textareaField("body", "Body", ".gallery-preview-intro"),
            backgroundImageField(
              "image",
              "Gallery image",
              ".gallery-preview-card",
            ),
            textField("label", "Gallery label", ".gallery-preview-label"),
            textField("caption", "Gallery caption", "strong"),
          ],
          repeatable: {
            itemSelector: ".gallery-preview-card",
            labelSingular: "Gallery card",
            labelPlural: "Gallery cards",
          },
        },
      ],
    },
    {
      slug: "about",
      fileName: "about.html",
      title: "About",
      sections: [
        pageHero,
        {
          id: "story",
          label: "Story",
          selector: ".about-story-section",
          fields: [
            textField("eyebrow", "Eyebrow", ".section-kicker"),
            textField("title", "Title", "h2"),
            textareaField("body1", "Preview paragraph 1", "p:nth-of-type(1)"),
            textareaField("body2", "Preview paragraph 2", "p:nth-of-type(2)"),
            textField(
              "ctaText",
              "Read more button text",
              ".about-story-readmore",
            ),
            imageField("image", "Image", "img"),
          ],
        },
        {
          id: "story-modal",
          label: "Story Modal",
          selector: "#aboutStoryModal .modal-content",
          fields: [
            textField("eyebrow", "Eyebrow", ".modal-header .section-kicker"),
            textField("title", "Modal title", "#aboutStoryModalLabel"),
            textareaField("bodyHtml", "Full story", ".about-story-modal-body", {
              type: "richText",
              target: "innerHTML",
              helpText:
                "Paste the full story here. The editor will shorten the visible story preview to fit this template.",
            }),
          ],
        },
        {
          id: "principles",
          label: "Principles",
          selector: ".about-principles-section",
          fields: [
            textField("title", "Title", "h2"),
            textField("principleTitle", "Principle title", "h3"),
            textareaField("principleBody", "Principle body", "p"),
          ],
          repeatable: {
            itemSelector: ".principle-card, article",
            labelSingular: "Principle",
            labelPlural: "Principles",
          },
        },
        {
          id: "principal-note",
          label: "Principal Note",
          selector: ".principal-note-section",
          fields: [
            textField("title", "Title", "h2"),
            textareaField("body", "Body", "p"),
            imageField("image", "Image", "img"),
          ],
        },
        {
          id: "student-experience",
          label: "Student Experience",
          selector: ".student-experience-section",
          fields: [
            textField("eyebrow", "Eyebrow", ".section-kicker"),
            textField("title", "Title", "h2"),
            textareaField("body", "Body", ".section-copy, p"),
            textField("experienceTitle", "Experience title", "h3"),
            textareaField("experienceBody", "Experience body", "p"),
          ],
          repeatable: {
            itemSelector: "li, article, .experience-card",
            labelSingular: "Experience item",
            labelPlural: "Experience items",
          },
        },
        {
          id: "facts",
          label: "Facts",
          selector: ".about-facts-section",
          fields: [
            textField("eyebrow", "Eyebrow", ".section-kicker"),
            textField("title", "Title", "h2"),
            textField("factValue", "Fact value", "strong"),
            textField("factLabel", "Fact label", "span, p"),
          ],
          repeatable: {
            itemSelector: "article, .fact-card",
            labelSingular: "Fact",
            labelPlural: "Facts",
          },
        },
      ],
    },
    {
      slug: "academics",
      fileName: "academics.html",
      title: "Academics",
      sections: [
        pageHero,
        {
          id: "overview",
          label: "Overview",
          selector: ".academics-overview-section",
          fields: [
            backgroundImageField("image", "Image", ".academics-overview-media"),
            textField("eyebrow", "Eyebrow", ".section-kicker"),
            textField("title", "Title", "h2"),
            textareaField("body", "Body", "p"),
          ],
        },
        {
          id: "pathways",
          label: "Academic Pathways",
          selector: ".academics-pathways-section",
          fields: [
            textField("title", "Title", "h2"),
            textareaField("intro", "Intro", ".section-intro"),
            textField("pathwayLabel", "Pathway label", ".pathway-label"),
            textField("pathwayTitle", "Pathway title", ".pathway-card h3"),
            textareaField("pathwayBody", "Pathway body", ".pathway-card p"),
          ],
          repeatable: {
            itemSelector: ".pathway-card",
            labelSingular: "Pathway",
            labelPlural: "Pathways",
          },
        },
        {
          id: "learning-model",
          label: "Learning Model",
          selector: ".academics-learning-section",
          fields: [
            textField("eyebrow", "Eyebrow", ".section-kicker"),
            textField("title", "Title", "h2"),
            textareaField("body", "Body", ".section-copy, p"),
            textField("point", "Point", "li, .learning-point"),
          ],
          repeatable: {
            itemSelector: "li, .learning-point",
            labelSingular: "Learning point",
            labelPlural: "Learning points",
          },
        },
        {
          id: "student-support",
          label: "Student Support",
          selector: ".academics-support-section",
          fields: [
            textField("eyebrow", "Eyebrow", ".section-kicker"),
            textField("title", "Title", "h2"),
            textareaField("body", "Body", ".section-copy, p"),
            textField("supportTitle", "Support title", "h3"),
            textareaField("supportBody", "Support body", "p"),
          ],
          repeatable: {
            itemSelector: "article, .support-card",
            labelSingular: "Support card",
            labelPlural: "Support cards",
          },
        },
        {
          id: "outcomes",
          label: "Outcomes",
          selector: ".academics-outcomes-section",
          fields: [
            textField("title", "Title", "h2"),
            textField("outcomeValue", "Outcome value", "strong"),
            textField("outcomeLabel", "Outcome label", "span, p"),
          ],
          repeatable: {
            itemSelector: "article, .outcome-card",
            labelSingular: "Outcome",
            labelPlural: "Outcomes",
          },
        },
        {
          id: "academics-cta",
          label: "Academics CTA",
          selector: ".academics-page-cta",
          fields: [
            textField("title", "Title", "h2"),
            textareaField("body", "Body", "p"),
            textField("ctaText", "CTA text", ".btn, a"),
          ],
        },
      ],
    },
    {
      slug: "admissions",
      fileName: "admissions.html",
      title: "Admissions",
      sections: [
        pageHero,
        {
          id: "process",
          label: "Admissions Process",
          selector: ".admissions-process-section",
          fields: [
            textField("title", "Title", "h2"),
            textField("stepTitle", "Step title", "h3"),
            textareaField("stepBody", "Step body", "p"),
          ],
          repeatable: {
            itemSelector: "article, .process-card",
            labelSingular: "Process step",
            labelPlural: "Process steps",
          },
        },
        {
          id: "application-form-intro",
          label: "Application Form Intro",
          selector: ".admissions-form-section",
          fields: [
            textField("eyebrow", "Eyebrow", ".section-kicker"),
            textField("title", "Title", "h2"),
            textareaField("body", "Body", ".section-copy, p"),
          ],
        },
        {
          id: "highlights",
          label: "Admissions Highlights",
          selector: ".admissions-highlights-section",
          fields: [
            textField("highlightTitle", "Highlight title", "h3"),
            textareaField("highlightBody", "Highlight body", "p"),
          ],
          repeatable: {
            itemSelector: "article, .highlight-card",
            labelSingular: "Highlight",
            labelPlural: "Highlights",
          },
        },
        {
          id: "admissions-cta",
          label: "Admissions CTA",
          selector: ".admissions-page-cta",
          fields: [
            textField("title", "Title", "h2"),
            textareaField("body", "Body", "p"),
            textField("ctaText", "CTA text", ".btn, a"),
          ],
        },
      ],
    },
    {
      slug: "gallery",
      fileName: "gallery.html",
      title: "Gallery",
      sections: [
        pageHero,
        {
          id: "gallery-showcase",
          label: "Gallery Showcase",
          selector: ".gallery-showcase-section",
          fields: [
            backgroundImageField(
              "image",
              "Image",
              ".gallery-card, .gallery-item",
            ),
            textField("label", "Label", ".gallery-label"),
            textField("caption", "Caption", "strong, h3"),
          ],
          repeatable: {
            itemSelector: ".gallery-card, .gallery-item",
            labelSingular: "Gallery item",
            labelPlural: "Gallery items",
          },
        },
        {
          id: "gallery-cta",
          label: "Gallery CTA",
          selector: ".gallery-page-cta",
          fields: [
            textField("title", "Title", "h2"),
            textareaField("body", "Body", "p"),
            textField("ctaText", "CTA text", ".btn, a"),
          ],
        },
      ],
    },
    {
      slug: "contact",
      fileName: "contact.html",
      title: "Contact",
      sections: [
        pageHero,
        {
          id: "contact-details",
          label: "Contact Details",
          selector: ".contact-details-section",
          fields: [
            textField("title", "Title", "h2"),
            textField("phone", "Phone", "a[href^='tel:']"),
            textField("email", "Email", "a[href^='mailto:']"),
            textareaField("address", "Address", "address, p"),
          ],
        },
        {
          id: "contact-form",
          label: "Contact Form",
          selector: ".contact-form-section",
          fields: [
            textField("title", "Title", "h2"),
            textareaField("body", "Body", "p"),
          ],
        },
        {
          id: "contact-cta",
          label: "Contact CTA",
          selector: ".contact-page-cta",
          fields: [
            textField("title", "Title", "h2"),
            textareaField("body", "Body", "p"),
            textField("ctaText", "CTA text", ".btn, a"),
          ],
        },
      ],
    },
  ],
} satisfies SchoolTemplateManifest;
