import type { AudienceConfig } from "./types";

export const businessPlans: AudienceConfig = {
  id: "business",
  title: "Dexta For Businesses",
  subtitle: "Digital solutions tailored for your business growth",
  iconKey: "business",
  color: "cyan",
  reachPlans: [
    {
      name: "Reach",
      priceMonthly: "$99.99",
      priceQuarterly: "$280",
      priceMonthlyNaira: "₦30,220",
      priceQuarterlyNaira: "₦80,455",
      reachCount: "1,000+ persons",
      features: [
        "Visual Design (8 monthly)",
        "Content Management (3x weekly)",
        "Bulk SMS (up to 250 messages monthly)",
        "Online Platform (1x monthly)",
        "Automated Calls",
      ],
    },
    {
      name: "Reach Pro",
      priceMonthly: "$149.99",
      priceQuarterly: "$420",
      priceMonthlyNaira: "₦55,322",
      priceQuarterlyNaira: "₦150,566",
      reachCount: "2,000 persons",
      highlighted: true,
      features: [
        "Visual Design (12 monthly)",
        "Content Management (3x weekly)",
        "Bulk SMS (up to 250 messages monthly)",
        "Online Platform (1x monthly)",
        "Automated Calls (1hr + 1 voice over)",
      ],
    },
    {
      name: "Reach Max",
      priceMonthly: "$200",
      priceQuarterly: "$520",
      priceMonthlyNaira: "₦90,320",
      priceQuarterlyNaira: "₦250,599",
      reachCount: "5,000 persons",
      features: [
        "Visual Design (30 monthly)",
        "Content Management (7x weekly)",
        "Bulk SMS (up to 500 messages monthly)",
        "Online Platform (2x monthly)",
        "Automated Calls (3hrs + 1 voice over)",
      ],
    },
    {
      name: "Reach Mega",
      priceMonthly: "$299.99",
      priceQuarterly: "$820",
      priceMonthlyNaira: "₦150,455",
      priceQuarterlyNaira: "₦400,560",
      reachCount: "10,000 persons",
      features: [
        "Visual Design (Unlimited monthly)",
        "Content Management (21x weekly)",
        "Bulk SMS (up to 1000 messages monthly)",
        "Online Platform (4x monthly)",
        "Automated Calls (5hrs + 1 voice over)",
      ],
    },
  ],
  setupPlans: [
    {
      name: "Biz Lite",
      priceMonthly: "$199.99",
      priceQuarterly: "Contact Us",
      priceMonthlyNaira: "₦120,320",
      priceQuarterlyNaira: "Contact Us",
      description: "Let's set you up for success! Go digital with our set up offers.",
      features: [
        "Landing Page",
        "1 Year Free Domain Name",
        "1 Year Free Hosting",
        "Professional Email (1)",
        "Google My Business setup",
        "Social Media Page setup (2)",
        "1 Month Free Web Management",
      ],
    },
    {
      name: "Biz",
      priceMonthly: "$299.99",
      priceQuarterly: "Contact Us",
      priceMonthlyNaira: "₦250,700",
      priceQuarterlyNaira: "Contact Us",
      highlighted: true,
      features: [
        "Multipage Website",
        "1 Year Free Domain Name",
        "1 Year Free Hosting",
        "Professional Email (3)",
        "Google My Business setup",
        "Social Media Page setup (5)",
        "1 Month Free Web Management",
      ],
    },
    {
      name: "Biz+",
      priceMonthly: "Request Quote",
      priceQuarterly: "Request Quote",
      priceMonthlyNaira: "Request Quote",
      priceQuarterlyNaira: "Request Quote",
      features: [
        "Landing Page",
        "Web App or Mobile App",
        "1 Year Free Domain Name",
        "1 Year Free Hosting",
        "Professional Email (5)",
        "Google My Business setup",
        "Social Media Page setup (5)",
        "2 Months Free Web Management",
      ],
    },
  ],
};

export const schoolsPlans: AudienceConfig = {
  id: "schools",
  title: "Dexta For Schools",
  subtitle: "Educational digital transformation packages",
  iconKey: "schools",
  color: "blue",
  reachPlans: businessPlans.reachPlans,
  setupPlans: [
    {
      name: "Edu Lite",
      priceMonthly: "$199.99",
      priceQuarterly: "Contact Us",
      priceMonthlyNaira: "₦120,320",
      priceQuarterlyNaira: "Contact Us",
      features: [
        "Landing Page",
        "1 Year Free Domain Name",
        "1 Year Free Hosting",
        "Professional Email (1)",
        "Google My Business setup",
        "Social Media Page setup (2)",
        "1 Month Free Web Management",
      ],
    },
    {
      name: "Edu",
      priceMonthly: "$350",
      priceQuarterly: "Contact Us",
      priceMonthlyNaira: "₦285,700",
      priceQuarterlyNaira: "Contact Us",
      highlighted: true,
      features: [
        "Multipage Website",
        "1 Year Free Domain Name",
        "1 Year Free Hosting",
        "Professional Email (3)",
        "Google My Business setup",
        "Social Media Page setup (3)",
        "Digital Workspace setup (Google/Microsoft)",
        "1 Month Free Workspace Management",
        "Free Digital Workspace Training (4hrs)",
      ],
    },
    {
      name: "Edu+",
      priceMonthly: "Request Quote",
      priceQuarterly: "Request Quote",
      priceMonthlyNaira: "Request Quote",
      priceQuarterlyNaira: "Request Quote",
      features: [
        "Web App or Mobile App",
        "1 Year Free Domain Name",
        "1 Year Free Hosting",
        "Professional Email (5)",
        "Google My Business setup",
        "Social Media Page setup (5)",
        "Digital Workspace setup (Google/Microsoft)",
        "1 Month Free Workspace Management",
        "Free Digital Workspace Training (8hrs)",
      ],
    },
  ],
};

export const churchesPlans: AudienceConfig = {
  id: "churches",
  title: "Dexta For Churches & Organizations",
  subtitle: "Ministry and organization digital solutions",
  iconKey: "churches",
  color: "purple",
  reachPlans: businessPlans.reachPlans,
  setupPlans: [
    {
      name: "Lite",
      priceMonthly: "$199.99",
      priceQuarterly: "Contact Us",
      priceMonthlyNaira: "₦120,320",
      priceQuarterlyNaira: "Contact Us",
      features: [
        "Landing Page",
        "1 Year Free Domain Name",
        "1 Year Free Hosting",
        "Professional Email (1)",
        "Google My Business setup",
        "Social Media Page setup (2)",
        "1 Month Free Web Management",
      ],
    },
    {
      name: "Pro",
      priceMonthly: "Request Quote",
      priceQuarterly: "Request Quote",
      priceMonthlyNaira: "Request Quote",
      priceQuarterlyNaira: "Request Quote",
      highlighted: true,
      features: [
        "Multipage Website",
        "1 Year Free Domain Name",
        "1 Year Free Hosting",
        "Professional Email (3)",
        "Google My Business setup",
        "Social Media Page setup (3)",
        "1 Month Free Web Management",
      ],
    },
    {
      name: "Mega",
      priceMonthly: "Request Quote",
      priceQuarterly: "Request Quote",
      priceMonthlyNaira: "Request Quote",
      priceQuarterlyNaira: "Request Quote",
      features: [
        "Web App or Mobile App",
        "1 Year Free Domain Name",
        "1 Year Free Hosting",
        "Professional Email (5)",
        "Google My Business setup",
        "Social Media Page setup (5)",
        "2 Months Free Web Management",
      ],
    },
  ],
};


