import type { CSSProperties } from "react";
import type { AudienceColor } from "@/lib/offers-defaults";

type OffersThemeStyle = CSSProperties & Record<`--${string}`, string>;

export const OFFERS_THEME_STYLE: OffersThemeStyle = {
  "--offers-page-bg": "var(--background)",
  "--offers-page-surface": "var(--card)",
  "--offers-card-tint": "var(--card)",
  "--offers-page-surface-muted": "var(--card)",
  "--offers-page-surface-subtle": "var(--card)",
  "--offers-page-fg": "var(--dexta-secondary)",
  "--offers-page-fg-strong": "var(--dexta-secondary)",
  "--offers-page-muted": "var(--dexta-primary)",
  "--offers-page-muted-soft": "var(--dexta-secondary)",
  "--offers-page-border": "var(--dexta-primary)",
  "--offers-page-border-strong": "var(--dexta-secondary)",
  "--offers-hero-bg": "var(--dexta-secondary)",
  "--offers-hero-bg-strong": "var(--dexta-primary)",
  "--offers-hero-fg": "var(--primary-foreground)",
  "--offers-hero-muted": "var(--primary-foreground)",
  "--offers-hero-subtle": "var(--primary-foreground)",
  "--offers-hero-border": "var(--primary-foreground)",
  "--offers-hero-surface": "transparent",
  "--offers-hero-surface-strong": "var(--primary-foreground)",
  "--offers-brand-soft": "var(--dexta-primary)",
  "--offers-hero-glow-primary": "transparent",
  "--offers-hero-glow-secondary": "transparent",
  "--offers-card-fg": "var(--dexta-secondary)",
  "--offers-card-muted": "var(--dexta-secondary)",
  "--offers-card-border": "var(--dexta-primary)",
  "--offers-card-panel-bg": "var(--card)",
  "--offers-card-panel-fg": "var(--dexta-secondary)",
  "--offers-card-panel-muted": "var(--dexta-primary)",
  "--offers-card-badge-bg": "var(--card)",
  "--offers-card-badge-fg": "var(--dexta-secondary)",
  "--offers-shadow-soft": "none",
  "--offers-shadow-panel": "none",
  "--offers-shadow-hero": "none",
  "--offers-radius-panel": "1.875rem",
  "--offers-radius-card": "1.75rem",
  "--offers-radius-subcard": "1.5rem",
  "--offers-radius-toggle": "1.25rem",
  "--offers-radius-pill": "999px",
};

// Shared audience accents stay in the core Dexta blue palette.
const SHARED_AUDIENCE_ACCENT: OffersThemeStyle = {
  "--offers-accent": "var(--dexta-primary)",
  "--offers-accent-strong": "var(--dexta-secondary)",
  "--offers-accent-contrast": "var(--primary-foreground)",
  "--offers-accent-surface": "var(--card)",
  "--offers-accent-surface-strong": "var(--card)",
  "--offers-accent-border": "var(--dexta-primary)",
  "--offers-accent-border-strong": "var(--dexta-secondary)",
  "--offers-accent-soft": "var(--dexta-secondary)",
  "--offers-accent-muted": "var(--dexta-secondary)",
  "--offers-accent-glow": "transparent",
};

const AUDIENCE_ACCENTS: Record<AudienceColor, OffersThemeStyle> = {
  cyan: {
    ...SHARED_AUDIENCE_ACCENT,
    "--offers-card-tint": "var(--card)",
  },
  blue: {
    ...SHARED_AUDIENCE_ACCENT,
    "--offers-card-tint": "var(--card)",
  },
  green: {
    ...SHARED_AUDIENCE_ACCENT,
    "--offers-card-tint": "var(--card)",
  },
  purple: {
    ...SHARED_AUDIENCE_ACCENT,
    "--offers-card-tint": "var(--card)",
  },
};

const REACH_CARD_ACCENTS: Record<AudienceColor, OffersThemeStyle> = {
  blue: {
    "--offers-card-tint": "var(--dexta)",
    "--offers-accent": "var(--dexta)",
    "--offers-accent-strong": "var(--dexta-secondary)",
    "--offers-accent-contrast": "var(--dexta-secondary)",
    "--offers-accent-surface": "var(--card)",
    "--offers-accent-surface-strong": "var(--card)",
    "--offers-accent-border": "var(--dexta-secondary)",
    "--offers-accent-border-strong": "var(--dexta-secondary)",
    "--offers-accent-soft": "var(--dexta-secondary)",
    "--offers-accent-muted": "var(--dexta-secondary)",
    "--offers-accent-glow": "transparent",
    "--offers-card-fg": "var(--dexta-secondary)",
    "--offers-card-muted": "var(--dexta-secondary)",
    "--offers-card-border": "var(--dexta-secondary)",
    "--offers-card-panel-bg": "var(--card)",
    "--offers-card-panel-fg": "var(--dexta-secondary)",
    "--offers-card-panel-muted": "var(--dexta-primary)",
    "--offers-card-badge-bg": "var(--card)",
    "--offers-card-badge-fg": "var(--dexta-secondary)",
  },
  cyan: {
    "--offers-card-tint": "var(--dexta-primary)",
    "--offers-accent": "var(--dexta-primary)",
    "--offers-accent-strong": "var(--dexta-secondary)",
    "--offers-accent-contrast": "var(--primary-foreground)",
    "--offers-accent-surface": "var(--card)",
    "--offers-accent-surface-strong": "var(--card)",
    "--offers-accent-border": "var(--primary-foreground)",
    "--offers-accent-border-strong": "var(--primary-foreground)",
    "--offers-accent-soft": "var(--primary-foreground)",
    "--offers-accent-muted": "var(--primary-foreground)",
    "--offers-accent-glow": "transparent",
    "--offers-card-fg": "var(--primary-foreground)",
    "--offers-card-muted": "var(--primary-foreground)",
    "--offers-card-border": "var(--primary-foreground)",
    "--offers-card-panel-bg": "var(--card)",
    "--offers-card-panel-fg": "var(--dexta-secondary)",
    "--offers-card-panel-muted": "var(--dexta-primary)",
    "--offers-card-badge-bg": "var(--card)",
    "--offers-card-badge-fg": "var(--dexta-primary)",
  },
  purple: {
    "--offers-card-tint": "var(--dexta-secondary)",
    "--offers-accent": "var(--dexta-secondary)",
    "--offers-accent-strong": "var(--dexta-secondary)",
    "--offers-accent-contrast": "var(--primary-foreground)",
    "--offers-accent-surface": "var(--card)",
    "--offers-accent-surface-strong": "var(--card)",
    "--offers-accent-border": "var(--primary-foreground)",
    "--offers-accent-border-strong": "var(--primary-foreground)",
    "--offers-accent-soft": "var(--primary-foreground)",
    "--offers-accent-muted": "var(--primary-foreground)",
    "--offers-accent-glow": "transparent",
    "--offers-card-fg": "var(--primary-foreground)",
    "--offers-card-muted": "var(--primary-foreground)",
    "--offers-card-border": "var(--primary-foreground)",
    "--offers-card-panel-bg": "var(--card)",
    "--offers-card-panel-fg": "var(--dexta-secondary)",
    "--offers-card-panel-muted": "var(--dexta-primary)",
    "--offers-card-badge-bg": "var(--card)",
    "--offers-card-badge-fg": "var(--dexta-secondary)",
  },
  green: {
    "--offers-card-tint": "var(--dexta-primary)",
    "--offers-accent": "var(--dexta-primary)",
    "--offers-accent-strong": "var(--dexta-secondary)",
    "--offers-accent-contrast": "var(--primary-foreground)",
    "--offers-accent-surface": "var(--card)",
    "--offers-accent-surface-strong": "var(--card)",
    "--offers-accent-border": "var(--primary-foreground)",
    "--offers-accent-border-strong": "var(--primary-foreground)",
    "--offers-accent-soft": "var(--primary-foreground)",
    "--offers-accent-muted": "var(--primary-foreground)",
    "--offers-accent-glow": "transparent",
    "--offers-card-fg": "var(--primary-foreground)",
    "--offers-card-muted": "var(--primary-foreground)",
    "--offers-card-border": "var(--primary-foreground)",
    "--offers-card-panel-bg": "var(--card)",
    "--offers-card-panel-fg": "var(--dexta-secondary)",
    "--offers-card-panel-muted": "var(--dexta-primary)",
    "--offers-card-badge-bg": "var(--card)",
    "--offers-card-badge-fg": "var(--dexta-primary)",
  },
};

export function getOffersAccentStyle(color: AudienceColor): CSSProperties {
  return AUDIENCE_ACCENTS[color];
}

export function getOffersReachCardStyle(color: AudienceColor): CSSProperties {
  return REACH_CARD_ACCENTS[color];
}
